# Generated by Django 6.0.5 on 2026-06-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0005_injuryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='fpl', max_length=40)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('players_synced', models.PositiveIntegerField(default=0)),
                ('clubs_synced', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID from external football API (FPL).', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='data_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('fpl', 'Fantasy Premier League')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID from external football API (FPL).', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
