# Generated by Django 6.0.5 on 2026-06-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0006_datasynclog_club_external_id_player_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transfermarkt_id',
            field=models.PositiveIntegerField(blank=True, help_text='Player ID on Transfermarkt.', null=True),
        ),
        migrations.AlterField(
            model_name='injuryassessment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('MF', 'Полузащитник'), ('FW', 'Нападающий')], max_length=2),
        ),
    ]
